"""add likes_read_time

Revision ID: 98e606ad13b2
Revises: aac1a538cedc
Create Date: 2019-11-29 15:13:48.225616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e606ad13b2'
down_revision = 'aac1a538cedc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_received_likes_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_received_likes_read_time')
    # ### end Alembic commands ###
